version: '3'
services:
  app:
    build: .
    container_name: "ending_note_app"
    ports:
      - "4567:4567"
    volumes:
      - .:/ending_note
    depends_on:
      - db
    tty: true
    stdin_open: true

  db:
    image: mysql:5.6
    container_name: "ending_note_db"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

volumes:
  mysql-data:
