version: '3'
services:
  app:
    build:
      context: .
      dockerfile: "./docker/Dockerfile_ruby"
    container_name: "ending_note_app"
    ports:
      - "4567:4567"
    command: rackup -p 4567 -o 0.0.0.0
    volumes:
      - .:/ending_note
    depends_on:
      - db
    tty: true
    stdin_open: true

  front:
    build:
      context: .
      dockerfile: "./docker/Dockerfile_node"
    container_name: "ending_note_front"
    volumes: 
    - .:/ending_note
    tty: true
    stdin_open: true

  db:
    image: mysql:5.6
    container_name: "ending_note_db"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

volumes:
  mysql-data:
